blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('post_detail/<slug:slug_text>/', views.post_detail, name='post_detail'),
    path('all_articles/', views.allArticles, name='all_articles'),
    path('recruitment_articles/', views.recruitmentArticles, name='recruitment_articles'),
    path('recruitment_post_detail/<slug:slug_text>/', views.recruitment_post_detail, name='recruitment_post_detail'),
    path('editor/', views.editor, name='editor'),
    path('create_post/', views.create_post, name='create_post'),
    path('create_recruitment_post/', views.create_recruitment_post, name='create_recruitment_post')
]

drdoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from django.db.models.signals import pre_save
from drdoproject.utils import unique_slug_generator

# Create your models here.
class Post(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=128)
    slug = models.SlugField(null=True, blank=True)
    body = models.TextField()
    publish_date = models.DateField(auto_now='True')

    def __str__(self):
        return self.title

class RecruitmentPost(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=128)
    slug = models.SlugField(null=True, blank=True)
    body = models.TextField()
    publish_date = models.DateField(auto_now='True')

    def __str__(self):
        return self.title
    


class Picture(models.Model):
    objects = models.Manager()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    pic = models.ImageField()
    
    def __str__(self):
        return str(self.post)

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Post)
pre_save.connect(slug_generator, sender=RecruitmentPost)

blog/forms.py
from django import forms
from blog.models import Post, RecruitmentPost

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title', 'body')

        widgets = {
            'body':forms.Textarea(attrs={'class':'editable postcontent'})  
        }

class RecruitmentPostForm(forms.ModelForm):
    class Meta():
        model = RecruitmentPost
        fields = ('title', 'body')

        widgets = {
            'body':forms.Textarea(attrs={'class':'editable postcontent'})  
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Picture, RecruitmentPost
from .forms import PostForm, RecruitmentPostForm
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.
def home(request):
    articles = Post.objects.order_by('-id')
    r_articles = RecruitmentPost.objects.order_by('-id')
    return render(request, 'home.html', {'articles':articles, 'r_articles':r_articles})

def index(request):
    latest_post = Post.objects.latest('id')
    articles = Post.objects.order_by('-id')[1:6]
    r_articles = RecruitmentPost.objects.order_by('-id')
    return render(request, 'index.html', {'post':latest_post, 'articles':articles, 'r_articles':r_articles})

def post_detail(request, slug_text):
    post = Post.objects.filter(slug=slug_text)
    post = post.first()
    articles = Post.objects.exclude(slug=slug_text).order_by('-id')
    r_articles = RecruitmentPost.objects.order_by('-id')
    return render(request, 'index.html', {'post': post, 'articles':articles, 'r_articles':r_articles})

def allArticles(request):
    articles = Post.objects.order_by('-id')
    r_articles = RecruitmentPost.objects.order_by('-id')
    return render(request, 'all_articles.html', {'articles':articles, 'r_articles':r_articles})

def recruitmentArticles(request):
    articles = Post.objects.order_by('-id')
    r_articles = RecruitmentPost.objects.order_by('-id')
    return render(request, 'recruitments.html', {'articles':articles, 'r_articles':r_articles})

def recruitment_post_detail(request, slug_text):
    post = RecruitmentPost.objects.filter(slug=slug_text)
    post = post.first()
    articles = Post.objects.order_by('-id')
    r_articles = RecruitmentPost.objects.exclude(slug=slug_text).order_by('-id')
    return render(request, 'index.html', {'post': post, 'articles':articles, 'r_articles':r_articles})

@staff_member_required
def create_post(request):
    postForm = PostForm()
    files = request.FILES.getlist('images')
    if request.method == 'POST':
        postForm = PostForm(request.POST) 
        if postForm.is_valid():
            postForm.save(commit=True)
            post = Post.objects.latest('id')
            for f in files:
                Picture.objects.create(post=post,pic=f)
            return index(request)

    return render(request, 'create_post.html',{'form':postForm})

@staff_member_required
def create_recruitment_post(request):
    postForm = RecruitmentPostForm()
    if request.method == 'POST':
        postForm = RecruitmentPostForm(request.POST) 
        if postForm.is_valid():
            postForm.save(commit=True)
            return index(request)

    return render(request, 'create_recruitment_post.html',{'form':postForm})

@staff_member_required
def editor(request):
    return render(request, 'editor.html')

templates/all_articles.html
{% extends 'base.html' %}

{% block content %} 

<div class="col-md-12 col-lg-6 w-75 mx-auto p-3 order-lg-2">
    <h1>Informational Articles</h1>
    <hr>
    <div class="card-columns">
    {% for article in articles %}
    <div class="card">
        {% with article.picture_set.all.first as image %} 
        <img src="{{ MEDIA_URL}} {{ image.pic.url }}" class="card-img-top">
        {% endwith %}
        <div class="card-body">
            <h5 class="card-title m-0 p-0">{{ article.title }}</h5>
            <p class="card-text m-0 p-0">{{ article.body|safe|truncatechars:50 }}</p>
        </div>
        <div class="card-footer">
            <small class="text-muted">Published on, {{ article.publish_date }}</small>
        </div>
        <a href="{% url 'post_detail' slug_text=article.slug %}" class="stretched-link"></a>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Technology Focus</title>
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'index/css/bootstrap.min.css' %}">
    <!-- google font -->
    <link href='https://fonts.googleapis.com/css?family=Anton' rel='stylesheet'>
    <!-- main css -->
    <link type="text/css" rel="stylesheet" href="{% static 'index/css/main.css' %}">
    <!-- tab icon link -->
    <link rel = "icon" href="{% static 'index/img/logo1.png' %}" type = "image/x-icon"> 
    <!-- icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Medium editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- facebook comment plugin -->
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0"></script>
    <!--google material icon  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    
    
</head>
<body>

    <!-- header nav bar -->
<nav class="navbar navbar-expand-lg sticky-top" style="background-color: #04659e">
        <a class="navbar-brand ml-lg-5" href="/">    
            Technology Focus
            <img src="{% static 'index/img/logo2.png' %}" width="45" height="45" class="d-inline-block align-top">  
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <i class="material-icons" style="color: white;">menu</i>
        </button> 
  <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <a class="nav-item nav-link mx-2" href="/">Home</a>
      <a class="nav-item nav-link mx-2" href="/all_articles/">Informational Articles</a>
      <a class="nav-item nav-link mx-2" href="/recruitment_articles/">Recruitment Articles</a>
      <a class="nav-item nav-link mx-2" href="https://www.facebook.com/DRDOTECHNOVATION/">Facebook Page</a>
      <a class="nav-item nav-link mx-2" href="/">About Us</a>
    </div>
  </div>
</nav>
{% if request.user.is_staff %}
<div class=" p-3 " style="float: right;">
  <a href="{% url 'editor' %}?next=/" class="btn btn-lg m-3">Go to Editor</a>
  <a href="{% url 'logout' %}?next=/" class="btn btn-lg m-3">Logout</a>
  
</div>
  
{% endif %}


<div class="container-fluid">
    <div class="row">
        
        {% block content %} 
        
        {% endblock %}
        
        <!-- space for affiliated marketing -->
        <div class="col-md-12 col-lg-3 order-lg-3 p-3">
          <div class="col-12 ">
            <div class="row d-none d-lg-block">
              <script type="text/javascript" language="javascript">
                var aax_size='160x600';
                var aax_pubname = 'innovation0a7-21';
                var aax_src='302';
              </script>
              <script type="text/javascript" language="javascript" src="http://c.amazon-adsystem.com/aax2/assoc.js"></script>
            </div>

            <div class="row">
              <script type="text/javascript" language="javascript">
                    var aax_size='300x250';
                    var aax_pubname = 'innovation0a7-21';
                    var aax_src='302';
              </script>
              <script type="text/javascript" language="javascript" src="http://c.amazon-adsystem.com/aax2/assoc.js"></script>
            </div>
          </div>
         
        </div>

       
        <div id="content-2" class="col-md-12 col-lg-3 order-lg-1 p-3">
                    <!-- all articles -->
                    {% if request.get_full_path != "/all_articles/" %}
                    <a href="/all_articles/" class="btn btn-block w-75 mx-auto p-2 my-3" role="button">VIEW MORE ARTICLES <i class="fa fa-angle-double-right"></i></a>
                    <div class="row custom-scrollbar-css"  style="overflow: auto; max-height:400px; overflow-x: hidden">
                      <div class="card-deck list-group">
                          {% for article in articles|slice:"0:5" %}
                          <div class="card list-group-item list-group-item-action mx-auto w-75 my-2">
                              {% with article.picture_set.all.first as image %} 
                              <img src="{{ MEDIA_URL}} {{ image.pic.url }}" class="card-img-top">
                              {% endwith %}
                              <div class="card-body">
                                  <h5 class="card-title">{{ article.title }}</h5>
                                  <p class="card-text">{{ article.body|safe|truncatechars:50 }}</p>
                              </div>
                              <div class="card-footer">
                                  <small class="text-muted">Published on, {{ article.publish_date }}</small>
                              </div>
                              <a href="{% url 'post_detail' slug_text=article.slug %}" class="stretched-link"></a>
                          </div>
                          {% endfor %}
                      </div>
                      
                    </div>
            <hr>
            {% endif %}

          <!--recruitment articles  -->
          {% if request.get_full_path != "/recruitment_articles/" %}
          <a href="/recruitment_articles/" class="btn btn-block w-75 mx-auto p-2 my-3" role="button">RECRUITMENT ARTICLES <i class="fa fa-angle-double-right"></i></a>
          <div class="row custom-scrollbar-css" style="overflow: auto; max-height:300px;">
            {% for article in r_articles %}
            <div class="mx-auto w-75">
              <a href="{% url 'recruitment_post_detail' slug_text=article.slug %}"><h5 style="color: black;">{{ article.title }}</h5></a>
              <hr>
            </div>
            {% endfor %}
          </div>
          {% endif %}

          <!-- affiliated marketing -->
          {% if request.get_full_path == "/recruitment_articles/" or request.get_full_path == "/all_articles/" %}
          <div class="m-2">
            <script type="text/javascript" language="javascript">
              var aax_size='300x600';
              var aax_pubname = 'innovation0a7-21';
              var aax_src='302';
            </script>
            <script type="text/javascript" language="javascript" src="http://c.amazon-adsystem.com/aax2/assoc.js"></script>
          </div>
          
          {% endif %}

        </div>

    </div>      
</div>

<!-- footer -->
<footer>
    <div class="mt-5 pt-3 pb-3">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 col-xs-12 about-company">
              <h2>ABOUT US</h2>
              <p class="pr-5 text-white-50">Here we post <a href="/all_articles/">Informational articles</a> and <a href="/recruitment_articles/">recruitment information</a> compiled from government publications and authentic sources.</p>
              <p><a class="facebook" href="https://www.facebook.com/DRDOTECHNOVATION/"><i class="fa fa-facebook-square mr-1 facebook"></i>Technology Focus-MAGAZINE</a></p>
            </div>
            <div class="col-lg-6 col-xs-12">
              <h4 class="mt-lg-0 mt-sm-4">CONTACT US</h4>
              <p><i class="fa fa-envelope-o mr-3"></i><a class="facebook" href="mailto: technologyfocusmagazine@gmail.com">technologyfocusdrdo@gmail.com</a></p>
            </div>
          </div>
          <div class="row">
            <div class="col copyright">
              <small class="text-white-50">© 2020 technologyfocus. All Rights Reserved.</small>
            </div>
          </div>
        </div>
        </div>
</footer>
<!-- jquery -->
<script src="{% static 'index/js/jquery-3.4.1.min.js' %}"></script> 
<!-- bootstrap -->
<script src="{% static 'index/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/create_post.html
{% extends 'base.html' %}

{% block content %} 

<div class="col-md-12 col-lg-6 order-lg-2 p-3">
    
    <h1>Create a NEW Post</h1>
   
    <hr>
    <form method="post" autocomplete="off" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="file" name="images" multiple>
        <input type="submit" class='btn btn-primary' value="Post">
    </form>

    
</div>
<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

templates/create_recruitment_post.html
{% extends 'base.html' %}

{% block content %} 

<div class="col-md-12 col-lg-6 order-lg-2 p-3">

    <h1>Create a NEW Recruitment Post</h1>
   
    <hr>
    <form method="post" autocomplete="off" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="Post">
    </form>
</div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

templates/editor.html
{% extends 'base.html' %}

{% block content %} 

<div class="col-md-12 col-lg-6 order-lg-2 p-3">
    <div class="h-100 row align-items-center">
        <h1>What do you want to do?</h1>
        <a href="{% url 'create_post' %}" class="btn p-3 m-3">Create Informational Article</a>
        <a href="{% url 'create_recruitment_post' %}" class="btn p-3 m-3">Create Recruitment Article</a>
    </div>   
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %} 
{% load static %}

<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
<script src="{% static 'home/js/parallax.js' %}"></script>


<div class=" home container-fluid col-md-12 col-lg-6 order-lg-2 p-3">
    

<div class="row">
	<div class="home-container col-lg-6">
        	<ul id="scene">
            <li class="layer" data-depth=".1"><img src="{% static 'home/img/1-removebg-preview.png' %}"></li>
			<li class="layer" data-depth="1"><img src="{% static 'home/img/2-removebg-preview.png' %}"></li>
			<li class="layer" data-depth="-1"><img src="{% static 'home/img/3-removebg-preview.png' %}"></li>
			<li class="layer" data-depth="2"><img src="{% static 'home/img/4-removebg-preview.png' %}"></li>
			<!-- <li class="layer" data-depth="0.5"><img src="{% static 'home/img/5-removebg-preview.png' %}"></li> -->
		</ul>
    </div>
    <div class="col-lg-6 p-4 my-auto">
        <h4>What this website is all about?</h4>
        <hr>
        <h5><p> This place is for those technology enthusiasts who wish to know more and explore technology, especially of India.</p>
            <p>Here we post <a href="/all_articles/">Informational articles</a> covering various fields of technology, compiled from government publications and authentic sources. Along with these, you can find <a href="/recruitment_articles/">recruitment information</a>  from the government institutions of India.</p>
            <p>Through this medium, we wish the achievements of our nation reach its proud citizens and the rest of the globe.</p>
            <p>Got any question? <a href="mailto:technologyfocusmagazine@gmail.com">Contact</a> us. </p>
        </h5>
    </div>

</div>
</div>
	<script>
		var scene = document.getElementById('scene');
		var parallax = new Parallax(scene);
    </script>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %} 

<div class="col-md-12 col-lg-6 order-lg-2 p-3">
    <div class="container my-4">
        <div class="page-header">
            <h3>{{ post.title }}</h3>
            <small class="text-muted">Published on, {{ post.publish_date }}</small>

            {% if request.get_full_path != "/post_detail/" %}
            <div class=" float-right fb-share-button" data-href="http://127.0.0.1:8000/post_detail/{{post.slug}}" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fpost_detail%2Flatest-post%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
            {% elif request.get_full_path != "/recruitment_post_detail/" %}
            <div class=" float-right fb-share-button" data-href="http://127.0.0.1:8000/recruitment_post_detail/{{post.slug}}" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fpost_detail%2Flatest-post%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
            {% endif %}


            
            <hr>   
        </div>
    </div>

    <div id="carouselExampleIndicators" class="carousel slide my-4">
        <ol class="carousel-indicators">
            {% for image in post.picture_set.all %}
               <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
            {% endfor %}
        </ol>
            
        <div class="carousel-inner">
            {% for image in post.picture_set.all %} 
                <div class="carousel-item  {% if forloop.counter0 == 0 %}active{% endif %} ">
                    <img class="d-block w-100" src="{{ MEDIA_URL}} {{ image.pic.url }}" alt="First slide">
                </div>                  
            {% endfor %}
        </div>
        
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <p>{{ post.body|safe|linebreaks }}</p>    

    {% if request.get_full_path != "/post_detail/" %}
        <div class="fb-comments" data-href="http://127.0.0.1:8000/post_detail/{{post.slug}}" data-numposts="5" data-width=""></div>
    {% elif request.get_full_path != "/recruitment_post_detail/" %}
        <div class="fb-comments" data-href="http://127.0.0.1:8000/recruitment_post_detail/{{post.slug}}" data-numposts="5" data-width=""></div>
    {% endif %}
</div>

        
{% endblock %}

templates/recruitments.html
{% extends 'base.html' %}

{% block content %} 

<div class="col-md-12 col-lg-6 order-lg-2 p-3">
    <h1>Recruitment Articles</h1>
    <hr>
    {% for article in r_articles %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title m-0 p-0">{{ article.title }}</h5>
        </div>
        <div class="card-footer">
            <small class="text-muted">Published on, {{ article.publish_date }}</small>
        </div>
        <a href="{% url 'recruitment_post_detail' article.slug %}" class="stretched-link"></a>
    </div>
    {% endfor %}
    
</div>
{% endblock %}